### ISSUE TITLE
我很好奇为什么取消了下载功能

### ISSUE THREAD

**Issue by ghg6666678** [YuKongA/Updater#20]
我不知道您现在是不是被律师函了，但是我在这里能检测到正式版HyperOS，但是网上找不到下载包

**Comment by YuKongA** [comment]
我没有被律师函，也没有取消下载。

**Comment by suyizhang** [comment]
大佬下载链接在哪获取

**Comment by YuKongA** [comment]
只有正式版公测可以直接获取这种带参数链接，其他都需要登录拥有对应权限的账号才可以获取带参数链接。
此外，目前 K70 系列即使你账号有权限，也获取不到正式版公测以外的带参数链接。
