### ISSUE TITLE
找到了一个可以查询MIUI正式版内测的接口

### ISSUE THREAD

**Issue by RBHakureiReimu** [YuKongA/Updater#48]
如题，因为作者也是国人所以就用汉语了，

https://publish.sec.miui.com/pre-installed-app/index.html#/

上述来自于小米官方的网站可以查询MIUI内部内测包的最新版本，如图所示，如果官方内部有这个版本的包，就会显示包含预装应用，反之则会如图二所示提示未找到预装应用。
![Screenshot_2024-04-26-13-53-37-445_com microsoft emmx canary](https://github.com/YuKongA/Updater/assets/45761551/42a0a534-7820-4999-a73a-4756c8a964c1)
![Screenshot_2024-04-26-14-00-31-349_com microsoft emmx canary](https://github.com/YuKongA/Updater/assets/45761551/6e03a5f3-bc46-4bc6-a9cc-b3e5657d0b52)

**Comment by YuKongA** [comment]
https://srv.sec.miui.com/preapp/version/inquiry?operator=cn&versionName=V816.0.36.0.UNCCNXM
很简单的请求方式，不过也没啥意义。

**Comment by RBHakureiReimu** [comment]
> https://srv.sec.miui.com/preapp/version/inquiry?operator=cn&versionName=V816.0.36.0.UNCCNXM 很简单的请求方式，不过也没啥意义。

主要是不少人用大佬你开发的应用都是用来查询小米官方更新进度的（还有个去小米社区冲脸的逆天来着）
