### ISSUE TITLE
Redmi Pad Pro 5G未添加

### ISSUE THREAD

**Issue by nmmmea** [YuKongA/Updater#59]
ruan
UFSCNXM

**Comment by YuKongA** [comment]
好的，明天加上

**Comment by YuKongA** [comment]
> ruan UFSCNXM

这个机器最新版本是多少？完整系统版本

**Comment by YuKongA** [comment]
> ruan UFSCNXM

这个机器最新版本是多少？完整系统版本

**Comment by nmmmea** [comment]
OS1.0.1.0.UFSCNXM
好像还是正式版内测

**Comment by YuKongA** [comment]
> OS1.0.1.0.UFSCNXM 好像还是正式版内测

加了，你试试，我没权限获取不到内测
