### ISSUE TITLE
［功能建议］ 获取增量包链接

### ISSUE THREAD

**Issue by f559** [YuKongA/Updater#60]
如题，希望能增加获取增量包链接的功能（即自定义发送更新请求时的系统版本号）

**Comment by YuKongA** [comment]
> 如题，希望能增加获取增量包链接的功能（即自定义发送更新请求时的系统版本号）

后面有空了我写一下吧

**Comment by YuKongA** [comment]
> 如题，希望能增加获取增量包链接的功能（即自定义发送更新请求时的系统版本号）

我在隔壁 [Compose](https://github.com/YuKongA/UpdaterKMM/actions/runs/9399434529) 版本写了，你可以试下也没有问题

**Comment by YuKongA** [comment]
这里也简单写了下 [CI](https://github.com/YuKongA/Updater/actions/runs/9411785943)
